### PR TITLE
FIX: EDB Configuration bug fix

### PR DESCRIPTION
**Pull request by ring630**

### CODE REVIEW

**Comment by gkorompi** [comment]
@ring630 You have to push again in order for the PR title error to be resolved

**Comment by SMoraisAnsys** [comment]
> @ring630 You have to push again in order for the PR title error to be resolved

Not really, workflows can be triggered again without pushing again. I'm launching it back

**Comment by ring630** [comment]
> > @ring630 You have to push again in order for the PR title error to be resolved
> 
> Not really, workflows can be triggered again without pushing again. I'm launching it back

@SMoraisAnsys failed again, but the title is corrected

**Comment by ring630** [comment]
> > @ring630 You have to push again in order for the PR title error to be resolved
> 
> Not really, workflows can be triggered again without pushing again. I'm launching it back

@SMoraisAnsys everything's checked after re-pushing.

**Pull request merged**
