### PR TITLE
FEAT: Added find_points_along_lines method in GeometryOperators class

### PR DESCRIPTION
**Pull request by Alberto-DM**

### CODE REVIEW

**Review by svandenb-dev — DISMISSED** [review]
LGTM

**Review by svandenb-dev — DISMISSED** [review]
LGTM

**Review by SMoraisAnsys — DISMISSED** [review]
Following @svandenb-dev approval, I'll remove my comment.

The main point of my remark was base on two things:

- the fact that we have other test mocking simple data (and I proposed to follow that approach)
- the fixture that you use might is a bit complex

However, I don't want to nitpick and your code and test are clear and well implemented. Thanks for the contribution !

**Comment by Alberto-DM** [comment]
> Following @svandenb-dev approval, I'll remove my comment.
> 
> The main point of my remark was base on two things:
> 
> * the fact that we have other test mocking simple data (and I proposed to follow that approach)
> * the fixture that you use might is a bit complex
> 
> However, I don't want to nitpick and your code and test are clear and well implemented. Thanks for the contribution !

I simplified the fixture. So the second point is addressed.

**Review by svandenb-dev — APPROVED** [review]
LGTM

**Pull request merged**
