### PR TITLE
CHORE: Update code base to use AEDT 24.2

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
Upgrading our code base to use AEDT 24.2 as default version.

@svandenb-dev @ring630 One of the changes that was performed comes from the fix of @Samuelopez-ansys in [68b393a](https://github.com/ansys/pyedb/pull/713/commits/68b393a08d45f89ad3a843cad939ce52b1ac3eee) It seems that AEDT 24.2 has changed the way it works with waveport naming. Previously, it changed the name on the fly and it is not the case anymore with 24.2. The fix consists in mocking what was performed previously with the naming so that 24.1 and 24.2 are both working !

### CODE REVIEW

**Comment by ring630** [comment]
> @ring630 I just tried to move to AEDT 24.2 and it seems that some examples are not working atm. Did you try the new version yourself ?

@SMoraisAnsys I tested some of the examples. They are working properly. Which ones are failing for you?

**Comment by ring630** [comment]
Can we use a globle variable to specify edb version?

**Comment by SMoraisAnsys** [comment]
> > @ring630 I just tried to move to AEDT 24.2 and it seems that some examples are not working atm. Did you try the new version yourself ?
> 
> @SMoraisAnsys I tested some of the examples. They are working properly. Which ones are failing for you?

It's not for me it's for the documentation, see the action log bellow

image

**Comment by ring630** [comment]
> > > @ring630 I just tried to move to AEDT 24.2 and it seems that some examples are not working atm. Did you try the new version yourself ?
> > 
> > 
> > @SMoraisAnsys I tested some of the examples. They are working properly. Which ones are failing for you?
> 
> It's not for me it's for the documentation, see the action log bellow
> 
> image
> 
> AttributeError: 'bool' object has no attribute 'plot'

This example works fine on my computer. Error msg in above indicates there is no solution data, which means the design may not be solved. h3d is part of pyaedt. Is it possible the failure is on pyaedt?

**Review by ring630 — APPROVED** [review]
LGTM

**Pull request merged**
