### PR TITLE
REFACTOR: edb configuration documentation

### PR DESCRIPTION
**Pull request by ring630**
- group edb configuration examples into two
- format fix in two examples

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
Updating the branch after main fix

**Review by SMoraisAnsys — CHANGES_REQUESTED** [review]
It might be better to set the thumbnail directly from the conf.py file. You just have to update the _static folder with the png. This will simplify the rst files to make them more readable.

Here is an example:

```python
# Sphinx gallery customization
nbsphinx_thumbnails = {
    "examples/use_configuration/import_ports": "_static/thumbnails/101_getting_started.png",
}
```

**Comment by ring630** [comment]
> ```python
> thumbnails
> ```

@SMoraisAnsys  Done

**Review by SMoraisAnsys — CHANGES_REQUESTED** [review]
I downloaded the artifact and the result is not working as expected, see bellow

image

Can you try it locally to fix it ?

**Comment by SMoraisAnsys** [comment]
> > ```python
> > thumbnails
> > ```
> 
> @SMoraisAnsys Done

You didn't modify the conf.py file, see the result in my previous comment.

**Comment by ring630** [comment]
> > > ```python
> > > thumbnails
> > > ```
> > 
> > 
> > @SMoraisAnsys Done
> 
> You didn't modify the conf.py file, see the result in my previous comment.

Ok. Updated.

**Comment by SMoraisAnsys** [comment]
Did you test it locally ? I downloaded the artifact and got the following result

image

Is it from my side or something you also experience ?

**Comment by ring630** [comment]
@SMoraisAnsys I see the same on my local machine. Not sure what I should do to fix it.

**Comment by SMoraisAnsys** [comment]
@ring630 I tested locally and the fix of path worked !

**Pull request merged**
