### PR TITLE
FEAT: EDB Config - export component properties

### PR DESCRIPTION
**Pull request by ring630**

### CODE REVIEW

**Review by SMoraisAnsys — COMMENTED** [review]
Could the method added to components by made into python properties instead of get/set calls ? Btw, is there a reason to remove the classes `CfgXXXProperties` ?

**Comment by ring630** [comment]
> Could the method added to components by made into python properties instead of get/set calls ? Btw, is there a reason to remove the classes `CfgXXXProperties` ?
get/set is replaced by property in the coming commit. 

I do not find the value of CfgXXXProperties. The less the better. I will bring them back when we need them.

**Review by svandenb-dev — APPROVED** [review]
LGTM

**Review by svandenb-dev — APPROVED** [review]
LGTM

**Pull request merged**
